services:
  backend:
    image: graphql_demo_backend
    build:
      context: .
      dockerfile: GraphQLDemo/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "GraphQLDemo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: